try
{
    throw new Exception("my first exception");
}
catch
{

}




